// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Loc",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Loc",
            targets: ["AppModule"],
            bundleIdentifier: "co.hartl.Loc",
            teamIdentifier: "9E8SXF3Y36",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "Use Images in Diary"),
                .locationAlwaysAndWhenInUse(purposeString: "Use Location in diary entries"),
                .locationWhenInUse(purposeString: "Use Location in diary entries")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)